name: docs

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Fix update time
      run: git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done 
    - 
      name: depoly
      uses: tool3/docsify-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
